replicaCount: 1

controller:
  enabled: false  # 꼭 꺼줘야 KRaft 모드 OFF됨

kraft:
  enabled: false

auth:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 1
  auth:
    enabled: false

externalZookeeper:
  enabled: false

service:
  type: ClusterIP
  ports:
    client: 9092

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 32000
  autoDiscovery:
    enabled: false
  broker:
    advertisedListeners:
      - PLAINTEXT://192.168.5.15:32000

configurationOverrides:
  listener.security.protocol.map: INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  listeners: INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094
  advertised.listeners: INTERNAL://my-kafka-0.my-kafka-headless.default.svc.cluster.local:9093,CLIENT://my-kafka-0.my-kafka-headless.default.svc.cluster.local:9092,EXTERNAL://localhost:32000
  inter.broker.listener.name: INTERNAL
  listener.name.external.plaintext.host: 0.0.0.0


#configurationOverrides:
#  listener.security.protocol.map: PLAINTEXT:PLAINTEXT
#  listeners: PLAINTEXT://:9092
#  advertised.listeners: PLAINTEXT://my-kafka.default.svc.cluster.local:9092
#  inter.broker.listener.name: PLAINTEXT